### ISSUE TITLE
Zarr can raise exceptions off the main thread when creating directories

### ISSUE THREAD

**Issue by andy-sweet** [acquire-project/acquire-driver-zarr#115]
Observed when writing a [spinnaker (blackfly) + zarr integration test on Windows](https://gist.github.com/andy-sweet/12653977cc51643b8a2b90c6cedd9591). This was flaky, but I got pretty predictable failures with 100 frames.

The test aborted when the main thread was calling `acquire_stop`. The zarr writer is in the process of emptying its queue of tasks, but has a while to go (the queue has a size of 36). See the [output logs for more details about progress](https://gist.github.com/andy-sweet/d373be86be2d2698734fa8da1bdc81ed).

One of the zarr writer threads threw using filesystem_error. It was attempting to create `out.zarr\\0/8/0/0` (when only `out.zarr/0|1|2|3` were created so far).  When calling `filesystem::create_directories` in the Windows std implementation, we got `error_code._MyVal == 3`.

Not sure why the error is occurring or how to fix it, but we should ensure that we're handling exceptions on the zarr worker threads so that they can be reported as error codes.

**Comment by aliddell** [comment]
I can't reproduce this locally, but I can fix the call to `filesystem::create_directories`.
