### ISSUE TITLE
In-progress .zarr stores do not open 

### ISSUE THREAD

**Issue by talonchandler** [acquire-project/acquire-driver-zarr#231]
I think this is an issue with metadata handling.   

I started a several-minutes-long acquisition, then I tried opening the in-progress .zarr in napari with the `napari-ome-zarr` plugin where I received an error `"ArrayNotFoundError: array not found at path %r' ‘0’”` with the [attached stack trace](https://github.com/acquire-project/acquire-driver-zarr/files/14225029/open-in-progress-zarr-stack-trace.txt). After the acquisition completes, the `.zarr` opens as expected.  

In case it’s helpful here are google drive links to the:
- [in-progress, broken zarr](https://drive.google.com/drive/folders/1IBPhtmbCX2c9kYSQWf7ecgJ5JB0C04MO?usp=drive_link)
- [finished working zarr](https://drive.google.com/drive/folders/1Jhl2wNWisp3gVETrBWFp_VVAp9r9eG6d?usp=drive_link)

@ziw-liu noticed that the `.zarray` file was missing from the in-progress .zarr. Can a minimal `.zarray` file be written at the start of an acquisition?

**Comment by ziw-liu** [comment]
I also notices that the array-level `.zattrs` file contains the expected shape for both incomplete and complete datasets. So that information is available at array creation time.

**Comment by aliddell** [comment]
The writer currently writes metadata at the beginning of acquisition and once acquisition stops, but we could also think about having the writer write metadata every time chunks are flushed to disk. It's one or two more hits to the filesystem, so it will slow performance somewhat. It may not be noticeable but we could do some experiments to find out.
