### ISSUE TITLE
Support ragged shards that have empty chunks

### ISSUE THREAD

**Issue by nclack** [acquire-project/acquire-driver-zarr#234]
Suppose we had 

frames of size (14192,10640) px 
chunks of size (128,128) px
shards of size (1024,1024) px 

14192/1024 = 13.85 so we can conclude the shards are ragged, something we want to support

Looking at the remainder

0.85*1024 = 871 which is larger than the chunk size.

So, not all chunks in the shard are "hit" by a frame.  Some are empty.

The Zarr v3 sharding specification should support this; not all chunks must be present. 

However, the writer doesn't like that; the frame must partially hit each chunk.  We should change that behavior.  I suspect we can simply not emit those chunks.

**Comment by aliddell** [comment]
Closed by #236
