### ISSUE TITLE
Read and validate zarr JSON in tests

### ISSUE THREAD

**Issue by andy-sweet** [acquire-project/acquire-driver-zarr#46]
In acquire-project/cpx#110, we added a third party JSON library to write JSON.

That functionality is tested via the Python tests in an integrated way, but having more unit-like tests closer to the C++ implementation could be helpful during development and debugging.

The main goal of this task is to modify the existing zarr tests to use the same JSON library to at least read and validate the written JSON files. We could also pick some critical attributes (e.g. axes) to inspect and assert conditions about.

**Comment by aliddell** [comment]
Somewhere in there this got done.
